const defaultSeats = {
    "A": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "B": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "C": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "D": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "E": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "F": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "G": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "H": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "I": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "J": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "K": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "L": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ],
    "M": [
        { "col": "1", "isAvailable": true, "isSelected": false },
        { "col": "2", "isAvailable": true, "isSelected": false },
        { "col": "3", "isAvailable": true, "isSelected": false },
        { "col": "4", "isAvailable": true, "isSelected": false },
        { "col": "5", "isAvailable": true, "isSelected": false },
        { "col": "6", "isAvailable": true, "isSelected": false },
        { "col": "7", "isAvailable": true, "isSelected": false },
        { "col": "8", "isAvailable": true, "isSelected": false },
        { "col": "9", "isAvailable": true, "isSelected": false },
        { "col": "10", "isAvailable": true, "isSelected": false },
        { "col": "11", "isAvailable": true, "isSelected": false },
        { "col": "12", "isAvailable": true, "isSelected": false }
    ]
}

module.exports = defaultSeats;